LangString addOrReinstall ${LANG_POLISH} "Dodaj/zainstaluj ponownie składniki"
LangString alreadyInstalled ${LANG_POLISH} "Już zainstalowano"
LangString alreadyInstalledLong ${LANG_POLISH} "${PRODUCTNAME} ${VERSION} jest już zainstalowany. Wybierz operację, którą chcesz wykonać, i kliknij Dalej, aby kontynuować."
LangString appRunning ${LANG_POLISH} "{{product_name}} jest uruchomiony! Zamknij go najpierw i spróbuj ponownie."
LangString appRunningOkKill ${LANG_POLISH} "{{product_name}} jest uruchomiony!$
Kliknij OK, aby go zamknąć"
LangString chooseMaintenanceOption ${LANG_POLISH} "Wybierz operację do wykonania."
LangString choowHowToInstall ${LANG_POLISH} "Wybierz sposób instalacji ${PRODUCTNAME}."
LangString createDesktop ${LANG_POLISH} "Utwórz skrót na pulpicie"
LangString dontUninstall ${LANG_POLISH} "Nie odinstalowuj"
LangString dontUninstallDowngrade ${LANG_POLISH} "Nie odinstalowuj (instalacja starszej wersji bez odinstalowania jest wyłączona w tym instalatorze)"
LangString failedToKillApp ${LANG_POLISH} "Nie udało się zamknąć {{product_name}}. Zamknij program ręcznie i spróbuj ponownie"
LangString installingWebview2 ${LANG_POLISH} "Instalowanie WebView2..."
LangString newerVersionInstalled ${LANG_POLISH} "Nowsza wersja ${PRODUCTNAME} jest już zainstalowana! Instalowanie starszej wersji nie jest zalecane. Jeśli naprawdę chcesz to zrobić, lepiej najpierw odinstaluj obecną wersję. Wybierz operację, którą chcesz wykonać, i kliknij Dalej, aby kontynuować."
LangString older ${LANG_POLISH} "starsza"
LangString olderOrUnknownVersionInstalled ${LANG_POLISH} "W systemie zainstalowana jest $R4 wersja ${PRODUCTNAME}. Zalecane jest odinstalowanie obecnej wersji przed instalacją. Wybierz operację, którą chcesz wykonać, i kliknij Dalej, aby kontynuować."
LangString silentDowngrades ${LANG_POLISH} "Instalacja starszej wersji jest wyłączona w tym instalatorze, więc tryb cichy nie może być kontynuowany. Użyj instalatora w trybie graficznym.$
"
LangString unableToUninstall ${LANG_POLISH} "Nie można odinstalować!"
LangString uninstallApp ${LANG_POLISH} "Odinstaluj ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_POLISH} "Odinstaluj przed instalacją"
LangString unknown ${LANG_POLISH} "nieznana"
LangString webview2AbortError ${LANG_POLISH} "Nie udało się zainstalować WebView2! Aplikacja bez niego nie zadziała. Spróbuj uruchomić instalator ponownie."
LangString webview2DownloadError ${LANG_POLISH} "Błąd: pobieranie WebView2 nie powiodło się - $0"
LangString webview2DownloadSuccess ${LANG_POLISH} "Pomyślnie pobrano instalator WebView2"
LangString webview2Downloading ${LANG_POLISH} "Pobieranie instalatora WebView2..."
LangString webview2InstallError ${LANG_POLISH} "Błąd: instalacja WebView2 zakończyła się kodem $1"
LangString webview2InstallSuccess ${LANG_POLISH} "Pomyślnie zainstalowano WebView2"
LangString deleteAppData ${LANG_POLISH} "Usuń dane aplikacji"
