use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Matches the explicit column list every query in auth.rs selects (never
/// `SELECT *`) - `updated_at` isn't included since nothing reads it yet; a
/// later stage that adds profile editing brings it back then.
#[derive(sqlx::FromRow)]
pub struct User {
    pub id: Uuid,
    pub email: String,
    pub password_hash: String,
    pub display_name: String,
    pub created_at: DateTime<Utc>,
    /// True for an account somebody else created - see
    /// `migrations/0008_provisioned_accounts.sql`. While it holds, the
    /// account may only read its own profile and set a new password.
    pub must_change_password: bool,
}

/// What a client is ever shown about a user - `password_hash` never leaves
/// this service, not even to its own authenticated owner.
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UserProfile {
    pub id: Uuid,
    pub email: String,
    pub display_name: String,
    pub created_at: DateTime<Utc>,
    /// Told to the client so it can send the user straight to the change
    /// screen. The backend refuses everything else regardless, so this is
    /// for the interface's benefit, never the enforcement.
    pub must_change_password: bool,
}

impl From<&User> for UserProfile {
    fn from(user: &User) -> Self {
        UserProfile {
            id: user.id,
            email: user.email.clone(),
            display_name: user.display_name.clone(),
            created_at: user.created_at,
            must_change_password: user.must_change_password,
        }
    }
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RegisterRequest {
    pub email: String,
    pub password: String,
    pub display_name: String,
}

/// Replacing your own password. The current one is required even though the
/// caller is already authenticated: a token left behind on an unlocked
/// machine should not be enough to lock the real owner out of the account.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChangePasswordRequest {
    pub current_password: String,
    pub new_password: String,
}

/// Creating an account for somebody and putting them in the team, in one
/// step. The password is generated by the server, not supplied here - see
/// `password::generate_password` for why.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProvisionMemberRequest {
    pub email: String,
    /// Shown in the member list. Optional: the local part of the email is a
    /// reasonable stand-in until they set their own.
    pub display_name: Option<String>,
    /// The role to give them immediately. Optional, but the reason this
    /// exists: an account created without one can do nothing until somebody
    /// remembers to come back and assign it.
    pub role_id: Option<Uuid>,
}

/// The one and only time the generated password is readable.
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProvisionedMember {
    pub user: UserProfile,
    /// Stored only as an Argon2 hash; this is the plaintext, returned once
    /// and never obtainable again.
    pub temporary_password: String,
    pub role_assigned: bool,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoginRequest {
    pub email: String,
    pub password: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RefreshRequest {
    pub refresh_token: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AuthResponse {
    pub user: UserProfile,
    pub access_token: String,
    pub access_token_expires_at: i64,
    pub refresh_token: String,
}

#[derive(sqlx::FromRow, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Team {
    pub id: Uuid,
    pub name: String,
    pub owner_id: Uuid,
    pub created_at: DateTime<Utc>,
}

/// A row from `team_members` joined against `users` - everything a member
/// list needs to render without a second round trip per row.
#[derive(sqlx::FromRow, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TeamMember {
    pub user_id: Uuid,
    pub email: String,
    pub display_name: String,
    pub joined_at: DateTime<Utc>,
    pub is_owner: bool,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateTeamRequest {
    pub name: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AddMemberRequest {
    pub email: String,
}

#[derive(sqlx::FromRow, Serialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Role {
    pub id: Uuid,
    pub team_id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub is_system: bool,
    pub created_at: DateTime<Utc>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RoleWithPermissions {
    #[serde(flatten)]
    pub role: Role,
    pub permissions: Vec<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateRoleRequest {
    pub name: String,
    pub description: Option<String>,
    pub permissions: Vec<String>,
}

/// Full-replace semantics for `permissions` (like SshServerForm on the
/// desktop side always submitting the whole record) - simpler and less
/// error-prone than a partial add/remove-permission API for what's still a
/// short list per role.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateRoleRequest {
    pub name: String,
    pub description: Option<String>,
    pub permissions: Vec<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AssignRoleRequest {
    pub role_id: Uuid,
}

/// `status` here can be the computed value `"expired"` even though that's
/// never actually stored in the `status` column (see migrations/0005) -
/// every query that returns this type computes it at read time from
/// `status`/`expires_at` rather than trusting the raw column value.
#[derive(sqlx::FromRow, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Invitation {
    pub id: Uuid,
    pub team_id: Uuid,
    pub email: String,
    pub role_id: Option<Uuid>,
    pub status: String,
    pub invited_by: Option<Uuid>,
    pub created_at: DateTime<Utc>,
    pub expires_at: DateTime<Utc>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CreatedInvitation {
    #[serde(flatten)]
    pub invitation: Invitation,
    /// The raw, unhashed token - present only in this one response. Never
    /// retrievable again afterward, same as a freshly issued refresh token.
    pub token: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateInvitationRequest {
    pub email: String,
    pub role_id: Option<Uuid>,
    pub expires_in_days: Option<i64>,
}

/// `actor_id`/`actor_email`/`actor_display_name` are all nullable together -
/// null when the acting user's account has since been deleted (see
/// migrations/0004: `actor_id` is ON DELETE SET NULL specifically so the
/// event itself survives that, just without a resolvable actor anymore).
#[derive(sqlx::FromRow, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AuditEvent {
    pub id: Uuid,
    pub action: String,
    pub target_type: String,
    pub target_id: Option<Uuid>,
    pub result: String,
    pub metadata: serde_json::Value,
    pub created_at: DateTime<Utc>,
    pub actor_id: Option<Uuid>,
    pub actor_email: Option<String>,
    pub actor_display_name: Option<String>,
}

/// The public half of one device's SSH key.
///
/// Public by nature: this is the line an `authorized_keys` file holds in
/// plain text. The private half never leaves the machine that made it, and
/// this backend has no field for one - the same position
/// `TeamServer` takes on passwords.
#[derive(sqlx::FromRow, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DeviceKey {
    pub id: Uuid,
    pub user_id: Uuid,
    pub public_key: String,
    pub label: String,
    pub created_at: DateTime<Utc>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PublishDeviceKeyRequest {
    pub public_key: String,
    pub label: String,
}

/// One team member and the keys their devices have published, which is what
/// an install needs to give them an account on a shared Node.
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MemberAccess {
    pub user_id: Uuid,
    pub email: String,
    pub display_name: String,
    /// The Linux account this member is given on a Node. Derived from the
    /// user id rather than stored, the same way an Application's dedicated
    /// account is - one fewer thing that can disagree with itself.
    pub node_username: String,
    pub public_keys: Vec<String>,
}

/// One port an Application projects to its team. A snapshot, not the record
/// a runtime acts on.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TeamApplicationPort {
    pub name: String,
    pub protocol: String,
    pub internal_port: i32,
    pub external_port: Option<i32>,
    pub visibility: String,
}

/// One projected environment variable.
///
/// A secret one arrives with an empty `value` and `is_secret` set, rather
/// than not arriving at all. The distinction matters to the person reading:
/// an omitted `MYSQL_ROOT_PASSWORD` reads as "not configured", which would be
/// wrong and would send somebody to set one that already exists. The value
/// itself stays on the Node, in the Application's own environment file,
/// which is where the process reads it from.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TeamApplicationEnvironment {
    pub key: String,
    pub value: String,
    #[serde(default)]
    pub is_secret: bool,
}

#[derive(sqlx::FromRow, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TeamApplication {
    pub id: Uuid,
    pub team_id: Uuid,
    pub team_server_id: Option<Uuid>,
    /// The id the owning install knows it by, which is what makes a push
    /// idempotent rather than duplicating.
    pub local_id: Uuid,
    pub name: String,
    pub blueprint_id: String,
    pub runtime_type: String,
    pub working_directory: String,
    pub ports: serde_json::Value,
    pub environment: serde_json::Value,
    /// When this projection was last refreshed. A three-week-old snapshot is
    /// worth knowing about, and nothing else here would say so.
    pub updated_at: DateTime<Utc>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PushTeamApplicationRequest {
    pub local_id: Uuid,
    pub team_server_id: Option<Uuid>,
    pub name: String,
    pub blueprint_id: String,
    pub runtime_type: String,
    pub working_directory: String,
    #[serde(default)]
    pub ports: Vec<TeamApplicationPort>,
    #[serde(default)]
    pub environment: Vec<TeamApplicationEnvironment>,
}

/// Metadata only - no password/private-key-path/passphrase fields exist
/// here or in the table behind it (see migrations/0006). Secrets stay in
/// whichever device's OS keyring already has them.
#[derive(sqlx::FromRow, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TeamServer {
    pub id: Uuid,
    pub team_id: Uuid,
    pub name: String,
    pub host: String,
    pub ssh_port: i32,
    pub username: Option<String>,
    pub created_at: DateTime<Utc>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateTeamServerRequest {
    pub name: String,
    pub host: String,
    pub ssh_port: Option<i32>,
    pub username: Option<String>,
}
